### PR TITLE
Capstone Project HTML and Javascript

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Completed the project using Bootstrap Framework. It was a difficult project using something totally new but exciting as well at the same time. I learned a lot using this new framework and it showed how much could be accomplished using this framework. Easy to install and use. 

Deployment of the application was easy once you found the suitable classes for the elements. I am happy to have accomplished so much and hope for this project to get approved. 

I used a different theme, created my own images and logos, and used banners relevant to the theme. My theme was Solar Panel and Energy. So everything should be according to the theme. 

There have been some drawbacks or limitations to the Bootstrap framework. The close icon was a tough task to handle and work around. Also, the cards adjusted nicely, but in mobile view, there was little to no information on how to change the view and layout. 

I hope I  can fix them in the future.

### CODE REVIEW

**Comment by AsimKhan2019** [comment]
https://www.loom.com/share/5b5a57b6ca0349c8a7110348df7563af 

This is the Loom Video I made for my project. 

Thank you.

**Review by EricMbouwe — CHANGES_REQUESTED** [review]
Hi @AsimKhan2019, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
- [x] Your presentation video is not opening. Let's check what is happening there
- [x] You have a weird horizontal scroll on desktop sizes. A quick-win fix would be to use 
```
body {
  overflow-x: hidden;
}
```
Capture

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AsimKhan2019** [comment]
@EricMbouwe Thank you for the feedback, is there anything else in the project that I should focus on as well. Please kindly elaborate a little more for me. Thank you.

**Comment by AsimKhan2019** [comment]
https://www.loom.com/share/85fd18229ca44782beebaccab33a5f67

I just created a new video presentation for my project.

**Review by EricMbouwe — APPROVED** [review]
Hi @AsimKhan2019, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@EricMbouwe Thank you so much for the approval.

**Pull request merged**
